### PR TITLE
Added register storage feature.

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
 /kind new feature

**What this PR does / why we need it**:
This PR allows the user to register a storage device based on vendor and model.
user can select the Vendor and model and the appropriate (allowed) access info  and additional forms fields are dynamically populated. 
User has to enable one connection mechanism (either REST or SSH).

**Which issue(s) this PR fixes**:
Fixes #: #378 
- [x] Register storage page 
- [x] Accept access info params (REST or SSH)
- [x] Validate input
- [x] Register storage

**Test Report Added?**:
/kind TESTED

**Test Report**:
A short video demo: [Link](https://drive.google.com/file/d/1P3QBscUXRk_9HmdLZ-AA_2pZIuKTjz1o/view)

**Select Vendor and model to populate the form**
2  register-strorage-vendors

**Register Storage - Dell EMC - VMAX**
1  register-strorage-dell

**Register Storage - Huawei - OceanStor**
3  register-strorage-huawei

**Register Storage - HPE - 3PAR**
4  register-strorage-hpe

**Error while registering**
5  register-strorage-error-while-registering

**Successfully Registered**
6  register-strorage-registered-successfully

**Special notes for your reviewer**:

### CODE REVIEW

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Comment by kumarashit** [comment]
For VMAX and Ocenastor, only option is REST so why do we show the "Configure REST connection details" and Grey out the option? Why cannot we remove them, to avoid any confusion

**Comment by anvithks** [comment]
> For VMAX and Ocenastor, only option is REST so why do we show the "Configure REST connection details" and Grey out the option? Why cannot we remove them, to avoid any confusion

The code is written such that if only one access info is allowed then it is greyed out. If both SSH and REST are allowed then the user can switch one off. This will automatically make the other one required and not able to be hidden.

Going forward if there is a change and the user is allowed to provide SSH details then this will be taken care in the code.

**Review by skdwriting — APPROVED** [review]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Pull request merged**
