### PR TITLE
Removed legacy unused Cloud module. Renamed resource to infrastructure to match the frontend

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR cleans up the code structure and removes unused folders.
1. Removed the legacy `src/app/business/cloud` folder which was part of the original opensds code base but never used.
2. Renamed the `resource/` folder to `infrastructure/`. The `resource/` folder held the code that displayed the Infrastrucuture menu item in the frontend. 
3. 
**Which issue(s) this PR fixes**:

**Test Report Added?**:
/kind TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by skdwriting — COMMENTED** [review]
You mentioned Resource in the backend was shown as Infrastructure in the FE. Why not change Infrastructure in the FE to Resource?
What is the reason? FE naming is ok?!

**Comment by anvithks** [comment]
> You mentioned Resource in the backend was shown as Infrastructure in the FE. Why not change Infrastructure in the FE to Resource?
> What is the reason? FE naming is ok?!

In our current dashboard we are using the term resource to refer to Buckets, Volumes, FileShare and Storages.
The infrastructure section refers to the SODA backends (lvm backend, nfs backend, multicloud backends registered) 

The code had references to resource but we use the term infrastructure everywhere. this makes it confusing for any one referring to the code when we use resource.

hence the change.

**Comment by kumarashit** [comment]
IMHO, Can we hold on this PR and check few things before?
We need to confirm first: 
a) Are Volumes, File share, Buckets are really resource or something else like Storages?
b) LVM and NFS are infrastructure backends?
Once we are clear then it's better to rename. Else, if there is different opinion, again the changes

**Comment by anvithks** [comment]
> IMHO, Can we hold on this PR and check few things before?
> We need to confirm first:
> a) Are Volumes, File share, Buckets are really resource or something else like Storages?
> b) LVM and NFS are infrastructure backends?
> Once we are clear then it's better to rename. Else, if there is different opinion, again the changes

@kumarashit @skdwriting  With this PR the frontend and the code are aligned to reflect the same names.
We can raise an issue for this discussion and replace / remove the terms later based on the overall direction.
Anyone looking at the code at the moment will not know where to look for the code when they want to make changes to the infrastructure section.

**Comment by anvithks** [comment]
@kumarashit @skdwriting Raised an issue #519 to track this

**Comment by kumarashit** [comment]
> > IMHO, Can we hold on this PR and check few things before?
> > We need to confirm first:
> > a) Are Volumes, File share, Buckets are really resource or something else like Storages?
> > b) LVM and NFS are infrastructure backends?
> > Once we are clear then it's better to rename. Else, if there is different opinion, again the changes
> 
> @kumarashit @skdwriting With this PR the frontend and the code are aligned to reflect the same names.
> We can raise an issue for this discussion and replace / remove the terms later based on the overall direction.
> Anyone looking at the code at the moment will not know where to look for the code when they want to make changes to the infrastructure section.
If we decide to rename it to something different in FE, again the code need to be changed, isn't it? So why to have the repeated efforts? If we don't decide to change the names, then this PR is fine.

**Comment by anvithks** [comment]
> If we decide to rename it to something different in FE, again the code need to be changed, isn't it? So why to have the repeated efforts? If we don't decide to change the names, then this PR is fine.
> 

For clarity FE - >Front End. 

Yes. If it is decided that the entire naming convention needs to be changed then we may have to modify the front end. 
But this decision will take time and in the meanwhile this code will remain in this state. 
We have previously considered changing the naming but it was put on hold. 

Let's keep it on hold for now but I recommend we finalise the naming convention at the earliest.

**Comment by anvithks** [comment]
Closing this for now. Will reopen if needed.

**Pull request closed without merging**
