### PR TITLE
Fixed #470. Changed 'Create Host' to 'Register Host'

### LINKED ISSUE #470: Hosts should be discovered and not Created in the Resource Manager -> Hosts Page.
**Issue/Feature Description:**
Hosts should be discovered instead of Created in the Resource Manger Page . 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
 /kind enhancement

**What this PR does / why we need it**:
This PR changes the 'Create Host' nomenclature to 'Register Host'.
Under the host management section the user can register a new host by providing the necessary connection information. 
Creating a new host would involve the infrastructure provisioning, which we do not do. 
Hence the language is now changed to 'Register Host' as we are registering an already created host. 
The issue suggested we make it "Discover Host" but this change is going with the nomenclature we have used in Delfin for storage (Register Storage).
The associated changes have been made in Volume list and Orchestration create instance.

**Which issue(s) this PR fixes**:
Fixes #470 

**Test Report Added?**:
 /kind TESTED

**Test Report**:
register-host-button
register-host-page
register-host-volume-list

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by anvithks** [comment]
@skdwriting Please review and merge

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
