### PR TITLE
Added a search filter and removed the scroll from type selection during Register Backend

### LINKED ISSUE #583: User has to scroll to select the backend type while registering backend .
**Issue/Feature Description:**
When the user is registering a cloud backend the type selection dropdown shows a scroll . When more types are added to this list the user will have to scroll to select the type.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Adding a scroll to any drop down selection is not very user friendly.

**How to reproduce, in case of a bug:**
1. Login to SODA Dashboard
2. Click on the Register Backend button
3. Click on the Type dropdown.

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
backend-type-dropdown

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind enhancement

**What this PR does / why we need it**:
This PR fixes the scroll visible in the type selection during backend registration.
Additionally this PR also adds a search filter for the type selection dropdown to make it easier for the user to select the backend type.

**Which issue(s) this PR fixes**:
Fixes #583 

**Test Report Added?**:
/kind TESTED

**Test Report**:
type-select-filter-001
type-select-filter-002

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
Q: Will adding a "Vendor" dropdown to select the Vendor and then the Storage entity [Object, Block, File etc.] make  the list more organized,, instead of showing all the Backends in one long list.

**Review by rajat-soda — COMMENTED** [review]
Will adding a "Vendor" dropdown to select the Vendor and then the Storage entity [Object, Block, File etc.] make the list more organized,, instead of showing all the Backends in one long list.

**Comment by anvithks** [comment]
> Will adding a "Vendor" dropdown to select the Vendor and then the Storage entity [Object, Block, File etc.] make the list more organized,, instead of showing all the Backends in one long list.

@rajat-soda 
This works when all the vendors have multiple solutions. But some may not have any except object storage.
In which case we add an extra select step. just to select the one. I think the search works best since it is enhancing current dropdown. For now we can go with this but if all vendors that we support have multiple backend types then we can add the vendor dropdown.

**Comment by rajat-soda** [comment]
ok .lets add the vendor drop down , when we have sufficient data from majority of the vendors.

**Comment by rajat-soda** [comment]
LGTM

**Comment by anvithks** [comment]
> ok .lets add the vendor drop down , when we have sufficient data from majority of the vendors.

@rajat-soda @PravinRanjan10 
For this we will also need to revisit the way we have classified the types of backends,
The only way to distinguish vendors is by matching the `type` string of each backend. 
It would be beneficial if the types API returns a list based on the vendor and the supported backends for each. This way the user will get a classification even in the API response and not the Dashboard alone.

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by rajat-soda** [comment]
> > ok .lets add the vendor drop down , when we have sufficient data from majority of the vendors.
> 
> @rajat-soda @PravinRanjan10 
> For this we will also need to revisit the way we have classified the types of backends,
> The only way to distinguish vendors is by matching the `type` string of each backend. 
> It would be beneficial if the types API returns a list based on the vendor and the supported backends for each. This way the user will get a classification even in the API response and not the Dashboard alone.
> 
> Something like:
> ```jsonc
> {
>     "backends": {
>         "aws" : [
>             {
>             "label" : "aws-s3",
>             "type" : "object"
>             },
>             {
>             "label" : "aws-file",
>             "type" : "file"
>             },
>             {
>             "label" : "aws-block",
>             "type" : "block"
>             }
>         ],
>         "azure" : [
>             {
>             "label" : "azure-blob",
>             "type" : "object"
>             },
>             {
>             "label" : "azure-file",
>             "type" : "file"
>             }
>         ],
>         "gcp" : [
>             {
>             "label" : "gcp-s3",
>             "type" : "object"
>             },
>             {
>             "label" : "gcp-file",
>             "type" : "file"
>             }
>         ]
>     }
> }
> ```

Yes, makes sense

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Pull request merged**
