### PR TITLE
Removing for bucket field in ceph backend

### LINKED ISSUE #527: [Multicloud UI] Modify the register backend UI as per the changes made to the register backend process in the SODA Multicloud backend
**Issue/Feature Description:**
The current register backend process requires a bucket to be created on the cloud and the bucket name to be provided as an input.
As per the changes being made to the SODA multicloud backend users will now be able to create a bucket on the cloud from SODA multicloud. 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
To allow users to register a cloud backend without providing a bucket name.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by Click2cloud-Hebe**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:
With this PR we have updated ceph form for registering backend i.e. bucket field remove
**Which issue(s) this PR fixes**:

Fixes #527 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:
Ceph Form View
CEPH-UI

**Special notes for your reviewer**:

### CODE REVIEW

**Review by anvithks — APPROVED** [review]
LGTM

**Comment by kumarashit** [comment]
Please open corresponding issue and link it

**Comment by anvithks** [comment]
> Please open corresponding issue and link it

@kumarashit 
Since this also addresses #527 I have linked it in the description. 
Do we have to raise a separate issue for this PR?

**Comment by kumarashit** [comment]
Linking with #527 is fine..You can re-open that issue

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
