### PR TITLE
[Feature: Fixes#324] Added Multi-cloud File Share. List all, Create, Update, Delete, Batch Delete

### LINKED ISSUE #324: [Feature] User interface for Multi-cloud File Service
**Issue/Feature Description:**
Create a user interface to support the Multi-cloud File Service.
The current Cloud File Share or Filestore management should support:
- AWS EFS
- Azure File Share
- Google Cloud Filestore

Multi-cloud File Storage service will provide 
- Creation/Deletion/Updation of File shares
- Creating/Deleting/Updating the mount-targets
- Set/Un-set File Share Access Policies

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
The purpose is to provide a unified Data framework across core and cloud. Currently SODA Core projects already provide the native FileShare support for on-premise clusters. This support of Cloud FileShare/Storage will extend this support to Cloud.
The purpose is to narrow the gap between on-premise and Cloud File Storage access.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
 /kind new feature

**What this PR does / why we need it**:
This PR adds Multicloud file share feature. Users can perform the following:
- Create Cloud file share (AWS normal and encrypted and Azure)  
- List all File shares  
- Expand to view details of the file share  
- Modify File Share
- Delete File Share  
- Batch Delete file shares  

**Which issue(s) this PR fixes**:
Fixes #324 

**Test Report Added?**:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Add Storage Backend**
6 register-storage-backend  

**Create File share**

create-successful
create-aws-form
create-azure-form

**List all cloud file shares**
1 list-all-cloud-file-share

**Expand file share details**
list-all-exapnd

**Modify AWS File Share**
modify-aws-form

**Modify Azure Fileshare**
modify-azure-form

**Batch Delete Cloud File shares**
bathc-delete

**Delete Single file share**
4 delete-single-cloud-file-share

**Special notes for your reviewer**:
~Tested with mock data. Integration testing yet to be performed.~
Tested with backend.

### CODE REVIEW

**Comment by anvithks** [comment]
@kumarashit @skdwriting Please review

**Comment by skdwriting** [comment]
@anvithks looks ok. @kumarashit @himanshuvar please check on the keys and config information on the screens.
Can we do the integration test with the account and then merge this? please check and confirm

**Comment by kumarashit** [comment]
For Deleting multiple file shares, Can we show the list of Fileshares instead of just the number (2 Fileshare)?

**Comment by anvithks** [comment]
> For Deleting multiple file shares, Can we show the list of Fileshares instead of just the number (2 Fileshare)?

This is the way we show multiple delete across the application as of now. 
I can display the names of the file shares. But when there are many fileshares displaying names will make the message box very crowded. 
I think we can take this up as a enhancement in the new design.
I have raised an issue for this #349

**Comment by anvithks** [comment]
> For Deleting multiple file shares, Can we show the list of Fileshares instead of just the number (2 Fileshare)?

@kumarashit I have pushed this change as well. The batch delete screenshot in the description has the change.

**Pull request merged**
