### PR TITLE
Added Storage array Details. Added Volumes & pool component. Storage capacity and Alerts Tab

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind new feature
**What this PR does / why we need it**:
This PR lets the user view the details of a storage array on clicking the name of the storage device in the tree view, usable capacity widget, raw capacity widget and any other location where the storage device name can be linked.
This PR adds the following to the view:
- Storage array configuration overview
- Sync Storage device
- List all volumes associated with the array
- Expand the single volume to show details
- Hover on a volume to get quick overview
- List all pools associated with the array
- Expand the single pool to show details
- Hover on a pool to get quick overview
- Capacity tab with Chart view depicting current Usable Capacity
- Capacity tab with Chart view depicting current Raw Capacity
- Capacity Tab with charts for volumes and Storage pools capacity usage
- Alerts Tab listing latest alerts for storage device.
- Context menu support in the tree view in the storage summary page.
- Device Syncing status shown in tree view.

This PR also has some fixes in the code to remove redundant and unused code and corrected API calls to fetch volumes and storage pools by storage ID.

**Which issue(s) this PR fixes**:
Fixes #: 
#391 
- [x] Resources (Volumes, Storage Pools)
- [x]  Alerts
- [x]  Capacity Usage 
- [x]  Configuration information.  

#394 #396 #397 

**Test Report Added?**:
/kind TESTED

**Test Report**:
**Storage Array Details Overview - Configuration Tab**
details-overview-1

**Storage Array Syncing and trigger**
details-overview-syncing

**List all Volumes**
details-list-volumes

**Expand Volume Details**
details-list-volumes-expand-details

**Hover on Volume Name for quick overview**
details-list-volumes-hover-overview-1

details-list-volumes-hover-overview-2

**List all Pools**
details-list-pools

**Expand Pool Details**
details-list-pools-expand-details

**Hover on Volume Name for quick overview**
details-list-pools-hover-overview-1

details-list-pools-hover-overview-2

**Capacity Overview tab with Charts**

**Quick Capacity Usage Number**
capacity-dashboard-1

**Volumes and Storage pools capacity usage**
capacity-dashboard-2

**List Storage array alerts**
details-alerts-tab

**Added context menu to the Storage Device Tree view to allow user to perform the same device operations from the table list view.**
tree-context-menu

**Added Syncing status view in the tree view for devices.**
tree-syncing-icon

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by anvithks** [comment]
Added Some more information and charts to the Capacity Tab
capacity-dashboard-1
capacity-dashboard-2

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by anvithks** [comment]
> Change the Pink color
I am going to revisit the color scheme and will  come up with a  a color swatch for the overall feature. There are multiple colors and that is not looking very pleasing. 

I have added an issue #407 to track this.
Also added the `good-first-issue` and `StartMyContribution` labels.

**Comment by anvithks** [comment]
@kumarashit @NajmudheenCT @skdwriting 
Please review.

Added context menu to the Storage Device Tree view to allow user to perform the same device operations from the table list view.
tree-context-menu

Added Syncing status view in the tree view for devices.
tree-syncing-icon

**Comment by anvithks** [comment]
Added `No records found.` messages in the array usable and raw capacity widget when no storage devices are available.
no-records-found

**Review by NajmudheenCT — COMMENTED** [review]
1.regarding 'Quick Capacity Usage Number' : Is it a sum of all array capacities ? Is so Are you doing this calculation in dashbaord?
2. Do we need to show 'System used' ? Since we are not showing breakdown of 'RawCapacity' , I think there is no need to show 'System used' as this is a derived value, it may  confuse user !

**Comment by anvithks** [comment]
> 1.regarding 'Quick Capacity Usage Number' : Is it a sum of all array capacities ? Is so Are you doing this calculation in dashbaord?
This is for a particular Device. This is the Capacity Tab inside Storage Details. This calculation is received in the API for fetching details of a particular device. Some are calculated, for ex System used is calculated as we had discussed (Raw - Total usable)
Rest are all from the API.
For the Volumes and Pools I am calculating by summing all the capacities of the Volumes and pools associated with a Device.

> 2. Do we need to show 'System used' ? Since we are not showing breakdown of 'RawCapacity' , I think there is no need to show 'System used' as this is a derived value, it may confuse user !
This was done after we had discussed and I had shown in the initial screens of the home page. 
I can remove it but then we don't really have much to show in this page.

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
