### PR TITLE
Added support to register Hitachi VSP and IBM Storwize/SVC storage devices from dashboard

### LINKED ISSUE #475: [Delfin UI]Add support for new storage array vendors Hitachi and IBM
**Issue/Feature Description:**
Add support to dashboard to register storage arrays from Hitachi and IBM.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Delfin now supports two new vendors, Hitachi and IBM.
User can register the following new storage arrays:
1. Hitachi VSP
2. IBM Storwize / SVC

User should be able to register these devices from the dashboard.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind enhancement

**What this PR does / why we need it**:
This PR adds the support to register Hitachi VSP and IBM Storwize / SVC devices from the dashboard.
This PR also fixes some optimisation issues of constants and removed commented code.

**Which issue(s) this PR fixes**:
Fixes #475 #477 

**Test Report Added?**:
/kind TESTED

**Test Report**:
new-storage-1
new-storage-2-ibm
new-storage-3-hitachi

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by joseph-v** [comment]
What happens if user input 'Configure REST connection details?' to NO?

**Review by NajmudheenCT — COMMENTED** [review]
For SSH pub_key_type and pub_key is not mandatory..

**Comment by anvithks** [comment]
> What happens if user input 'Configure REST connection details?' to NO?

@joseph-v 
We have configured the forms based on the access mechanism that is allowed. 
Atleast one access mechanism is required the use cannot change the value. The switch is disabled.

**Comment by anvithks** [comment]
> For SSH pub_key_type and pub_key is not mandatory..

@NajmudheenCT 
The backend throws an error that the pub_key is a required property.
image

This is a sample request without the pub_key value
image

**Comment by kumarashit** [comment]
@anvithks @NajmudheenCT What is the conclusion for the above comment?

**Comment by NajmudheenCT** [comment]
> @anvithks @NajmudheenCT What is the conclusion for the above comment?

We may have backends with ssh , that do not need pub_key.. so mandating pub_key is not required. But for this a delfin fix is required. As of now we cant fixing this in delfin may imapct exisitng user and both supported backends need pub_key now. So I hope we can keep it like this for now.

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Comment by anvithks** [comment]
@kumarashit @skdwriting Please review and merge

**Review by skdwriting — APPROVED** [review]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Pull request merged**
