### PR TITLE
Fixed the issue of alerts getting overwritten by last entry.

### LINKED ISSUE #498: [Delfin UI] All alerts have same name and details. Alerts overwritten by last entry
**Issue/Feature Description:**
The alerts displayed in SODA Dashboard all have the same name and details but the alerts in alertmanager are shwoing correct information.
From SODA Dashboard
image

From Alertmanager
image

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind bug fix

**What this PR does / why we need it**:
This PR fixes the issue of all alerts having the same name and description in the alerts table.

**Which issue(s) this PR fixes**:
Fixes #498 

**Test Report Added?**:
/kind TESTED

**Test Report**:
image

image

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kumarashit** [comment]
@anvithks the reason this issue occurred and why this fix is required is not clear. Can you please elaborate?

**Comment by anvithks** [comment]
> @anvithks the reason this issue occurred and why this fix is required is not clear. Can you please elaborate?

I use an intermediate alert object to hold the values for a single alert that need to be displayed in our alerts table.
```
let alert = {
                    'alert_id' : '',
                    'alert_name' : '',
                    'severity' : '',
                    'category' : '',
                    'type' : '',
                    'sequence_number' : 0,
                    'occur_time' : 0,
                    'description' : '',
                    'resource_type' : '',
                    'location' : '',
                    'storage_id' : '',
                    'storage_name' : '',
                    'vendor' : '',
                    'model' : '',
                    'serial_number' : '',
                    'recovery_advice' : ''
                };
```
The response of the Alertmanager API returns alerts that are generated by two sources; Delfin and Prometheus.
Both have some minor differences in the number of parameters returned and the naming. 
I iterate through this array and create an array of objects that hold the final list of alerts that we see in  our table.

As per the previous [PR comment](https://github.com/sodafoundation/dashboard/pull/486#discussion_r546724636) I moved the object structure to a constant file and then just assigned it to the alerts variable as below:
```
let alert = Consts.STORAGES.alertDataModel;
```
This just made a shallow copy of the object and resulted in every iteration of the loop overwriting the previous values, instead of pushing it to the array.
More info [here](https://medium.com/@manjuladube/understanding-deep-and-shallow-copy-in-javascript-13438bad941c)

The alerts variable is just a temp that we use to push in to the array. I will check if there can be a better way, I think interfaces can be considered.

**Comment by kumarashit** [comment]
As you also said, this is not optimal solution so please open an Issue to track and try to get better solution

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
