### PR TITLE
Fixed console error on Storage Service plans page when no plans created. Added length check to backend var at line 124

### LINKED ISSUE #648: UI breaking because backend value not present
**Issue Description:**
we get a console error because the backend is not present we should add a proper check for backend values. if it is not present loop should not run.
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
UI might break in future
**How to reproduce, in case of a bug:**
go to the service page
Screenshot (5)

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

SodaCode2022

### PR DESCRIPTION
**Pull request by ravisaxena23**
**What type of PR is this?**
 /kind bug fix
 /kind cleanup

**What this PR does / why we need it**:
when someone tries to get all list items from the getAllLists function at line no 124 in service-plan.component.ts. the code breaks because the backend array length check is not present.

**Which issue(s) this PR fixes**:
Fixes #648 

**Test Report Added?**:
 /kind TESTED

**Test Report**:
Screenshot (6)

**Special notes for your reviewer**:

### CODE REVIEW

**Review by anvithks — APPROVED** [review]
LGTM

**Comment by anvithks** [comment]
#SODACODE-PR-ACCEPTED

**Comment by ravisaxena23** [comment]
Screenshot (15)
@anvithks  adding the new screenshot also I was checking one flow in which backends was undefined instead of the blank array so added a check for that also.

**Comment by anvithks** [comment]
@joseph-v Could you please review and approve.

**Review by joseph-v — APPROVED** [review]
LGTM

**Pull request merged**
