### PR TITLE
Added new storage resources to delfin UI: Controllers and Ports

### LINKED ISSUE #463: [Delfin UI] Add new resource types to storage device
**Issue/Feature Description:**
Add support for the following new resource types to Delfin UI

- [ ] Controllers
- [ ] Ports
- [ ] Disks

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Delfin now provides information about the Controllers, Ports and Disks associated with an array.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind enhancement

**What this PR does / why we need it**:
Added support for Controllers and Ports, new resource types to Delfin UI.
User can now see the list of controllers and ports associated with a storage array and also the details of the resource.

**Which issue(s) this PR fixes**:

Fixes #463 

**Test Report Added?**:
 /kind TESTED

**Test Report**:
**Controllers Tab**
controllers-tab-1

**Controllers Tab - View Details Expanded**
controllers-tab-expanded-details

**Overview of controller**
controllers-tab-overview

**Ports Tab**
ports-tab-1

**Ports Tab expanded details**
ports-tab-expanded-details

**Port overview**
ports-tab-overview

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kumarashit** [comment]
@NajmudheenCT @joseph-v Is it ok to keep the name as "Controller" "Ports" or will it have any impact if we show Host Ports in future

**Review by joseph-v — COMMENTED** [review]
LGTM

**Comment by NajmudheenCT** [comment]
> @NajmudheenCT @joseph-v Is it ok to keep the name as "Controller" "Ports" or will it have any impact if we show Host Ports in future

It is shown under the storage ( when you select details of a storage) So I guess it is ok to name like this.

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Comment by kumarashit** [comment]
> > @NajmudheenCT @joseph-v Is it ok to keep the name as "Controller" "Ports" or will it have any impact if we show Host Ports in future
> 
> It is shown under the storage ( when you select details of a storage) So I guess it is ok to name like this.

Ok, you mean the Masking view will be different and not under storage

**Comment by anvithks** [comment]
@kumarashit this is part of storage details - > Configuration tab.
Are host ports at the same level as storage arrays?

**Comment by kumarashit** [comment]
Host ports cannot be at same level as storage arrays.
Host ports become part of storage array config after masking

**Comment by NajmudheenCT** [comment]
> > > @NajmudheenCT @joseph-v Is it ok to keep the name as "Controller" "Ports" or will it have any impact if we show Host Ports in future
> > 
> > 
> > It is shown under the storage ( when you select details of a storage) So I guess it is ok to name like this.
> 
> Ok, you mean the Masking view will be different and not under storage

yes

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by kumarashit** [comment]
@NajmudheenCT @skdwriting Please check this

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
