### PR TITLE
Created a new file for the PoolService.Updated the references in all modules

### LINKED ISSUE #187: Create a separate file for pool.service instead of within profile.service
As per review comments in the PR #183 create a new file for pool service called pool.service.

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind enhancement

**What this PR does / why we need it**:
This PR separates the Pool service and Profile service from a single file and adds a new file for the pool service.
All the references to the PoolService are updated to reflect the new file.

**Which issue(s) this PR fixes**:

Fixes #187 

**Test Report Added?**:
/kind TESTED

**Test Report**:
The impact is in the profile list page. 
**Create Profile, List Profile**
image
**Modify Profile**
image

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kumarashit** [comment]
Can you just put the sanity result around this?

**Comment by anvithks** [comment]
@kumarashit updated the PR description with screenshots from the affected sections.

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Pull request merged**
