### PR TITLE
Added copy profile ID feature.

### LINKED ISSUE #575: [Feature Request] Can we have profile ID auto-copy mechanism for the Profiles in the profile list tab
**Feature Description:**
User should be able to copy the ProfileID for a particular Profiles in the Profile list Page

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
This feature is needed because in some SODA projects we need to enter the ProfileID in the yamls and users need to go to `osdsctl profile list` command to just get the Profile ID, 
IMO if we can give a way to user to get the profile ID from the dashboard then user need not go to command line

### PR DESCRIPTION
**Pull request by anvithks**
## Please merge #580 before merging this PR.
**What type of PR is this?**
/kind new feature

**What this PR does / why we need it**:
This PR adds the feature of allowing user to copy the profile ID in the profile list page.
This feature was requested by users as the profile ID is required in CSI integrations and some other places. Currently the users have to use the API with CURL or Postman to get the Profile ID or capture the profile ID from the dashboard developer toolbar.
This PR provides a simple copy button that user can click to copy the Profile ID.

**Which issue(s) this PR fixes**:
Fixes #575 

**Test Report Added?**:
/kind TESTED

**Test Report**:
copy-profile-id-001
copy-profile-id-002

**Special notes for your reviewer**:

### CODE REVIEW

**Review by asifdxtreme — APPROVED** [review]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Comment by skdwriting** [comment]
CI migration to github action. in progress. local CI ok. Merging

**Pull request merged**
