### PR TITLE
Removed the link to performance monitoring configuration from dashboard

### LINKED ISSUE #529: [Delfin UI] Change the performance metrics collection configuration from Dashboard based on the changes made to Delfin Performance framework.
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind enhancement

**What this PR does / why we need it**:
This PR removes the links to the performance metric collection configuration screens. 
The performance metrics collection configuration is now implicitly done at the time of device registration in Delfin.
The user does not have to manually configure a device to collect performance metrics.

**Which issue(s) this PR fixes**:
Fixes #529 

**Test Report Added?**:
/kind TESTED

**Test Report**:
remove-perf-config-1

remove-perf-config-2

remove-perf-config-3

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by NajmudheenCT — COMMENTED** [review]
LGTM . Please hold this till we merge all related  backend changes in delfin

**Comment by anvithks** [comment]
> LGTM . Please hold this till we merge all related  backend changes in delfin 

@NajmudheenCT I have added the on hold label. Please remove it when the connected PRs from delfin are merged

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
