### PR TITLE
[Fixes #332 & #333]Fixed the bug in create host page. Added hostname validation and some css fixes.

### LINKED ISSUE #332: Unaligned search box on cretae Host page
**Issue/Feature Description:**
While selecting availability zone, the text box appears un-aligned and odd placed [Ux issue]
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
The search box appears to be overlapping
**How to reproduce, in case of a bug:**
Go to add host page and select availability zone
**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

image

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind bug fix

**What this PR does / why we need it**:
This PR is required to fix issues raised in the Create Host page.

**Which issue(s) this PR fixes**:

Fixes #332 #333 

**Test Report Added?**:
/kind TESTED

**Test Report**:
Availability Zone dropdown
fixes332

Hostname Validation
fixes333

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by anvithks** [comment]
@kumarashit @NajmudheenCT Please review and merge.

**Comment by kumarashit** [comment]
Please raise PR on Master branch

**Comment by kumarashit** [comment]
Also, if the master is behind development, please raise PR to port the changes

**Comment by kumarashit** [comment]
Please sync to master

**Comment by anvithks** [comment]
@kumarashit  Closing since new PR is raised to master #336

**Pull request closed without merging**
