### PR TITLE
Added sidebar panel to home page. Improved register and show backends view

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
 /kind enhancement

**What this PR does / why we need it**:
This PR adds a new sidebar panel to the home page to improve the view of register storage, show backends list.
These were implemented with modals. In the register panel the dropdown to select the type of backends used to get internal scroll as here
## **Before**
current-register-1
**Dropdown scroll**
current-register-dropdown1

This has been fixed and the panel gives more space for display.

Going forward this panel can be used to perform all the operations. 

**Which issue(s) this PR fixes**:
Fixes #

**Test Report Added?**:
/kind TESTED

**Test Report**:

Demo video can be viewed here : **[DEMO VIDEO LINK](https://drive.google.com/file/d/1J2l4T98zv9Z5eSNolETiFrSWGU_7W6-b/view)**

**Register Backends**
sidebar-register-1
sidebar-register-2

**Show backends**
sidebar-backends-1

**Special notes for your reviewer**:

### CODE REVIEW

**Review by skdwriting — COMMENTED** [review]
Resource and Resource Manager --- is it not confusing?

**Comment by anvithks** [comment]
> Resource and Resource Manager --- is it not confusing?

I was thinking we can change `Resource` to `Datastore`
But it may have other implications.
Resource also has Hosts.

**Comment by anvithks** [comment]
@skdwriting Alternatively I was thinking of renaming `Resource Manager` to `Delfin SRM`
What are your thoughts?
@NajmudheenCT @kumarashit @wisererik What do you think?

**Comment by skdwriting** [comment]
How about just "Monitor" as of now?

**Comment by anvithks** [comment]
> How about just "Monitor" as of now?

We already have a Monitor menu item. It is used to link to the Grafana Dashboard and Alert Manager when Telemetry isinstalled. You can also configure the Prometheus, Grafana and Alert manager using the configuration page.

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by kumarashit** [comment]
> > How about just "Monitor" as of now?
> 
> 
> 
> We already have a Monitor menu item. It is used to link to the Grafana Dashboard and Alert Manager when Telemetry isinstalled. You can also configure the Prometheus, Grafana and Alert manager using the configuration page.
> 
> 

Can we simply call it “Storage Manager”?

**Comment by skdwriting** [comment]
> > > How about just "Monitor" as of now?
> > 
> > 
> > We already have a Monitor menu item. It is used to link to the Grafana Dashboard and Alert Manager when Telemetry isinstalled. You can also configure the Prometheus, Grafana and Alert manager using the configuration page.
> 
> Can we simply call it “Storage Manager”?

I think, resrouce, storage, all these confusing if you have multiple menu items.
Can we not obsolete the exciting telemetry feature? Fully focus to provide the monitoring through delfin?

@anvithks please raise an issue for this. It is not related to this PR anyways. Add the issue here. Then merge the PR

**Comment by anvithks** [comment]
@skdwriting will raise the issue.

**Comment by anvithks** [comment]
> > > > How about just "Monitor" as of now?
> > > 
> > > 
> > > We already have a Monitor menu item. It is used to link to the Grafana Dashboard and Alert Manager when Telemetry isinstalled. You can also configure the Prometheus, Grafana and Alert manager using the configuration page.
> > 
> > 
> > Can we simply call it “Storage Manager”?
> 
> I think, resrouce, storage, all these confusing if you have multiple menu items.
> Can we not obsolete the exciting telemetry feature? Fully focus to provide the monitoring through delfin?
> 
> @anvithks please raise an issue for this. It is not related to this PR anyways. Add the issue here. Then merge the PR

Tracking this discussion in #434

**Comment by anvithks** [comment]
Updated the style of the menu group item. 
Added description and better alignment of toggle switch
image

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
