### PR TITLE
Added multicloud archive/restore feature

### LINKED ISSUE #482: [Multicloud UI] Adding support for Cloud Archival and Retrieval [AWS]
**Issue/Feature Description:**
Allow the user to archive an object and specify the archival class.
Allow the user to restore/retrieve an object and specify the days and options.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
The SODA Multicloud service now supports enabling cloud archival and retrieval for AWS backends.
The user should be able to archive and retrieve objects from the dashboard.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**

/kind enhancement

**What this PR does / why we need it**:
This PR adds the multicloud archive and restore feature to SODA Dashboard.
Currently the following are working:
- Upload object to selected Tier
- List Archived object
- Download retrieved object (Retrieval enabled through postman)

ToDo:
- [ ] Fix the signature mismatch issue in restore.
This is being tracked here: #484 

**Which issue(s) this PR fixes**:
Fixes #482 

**Test Report Added?**:

 /kind TESTED

**Test Report**:
multicloud-archive-1

multicloud-archive-2

multicloud-archive-3

multicloud-archive-4

multicloud-archive-5

multicloud-archive-6

multicloud-archive-7

multicloud-restore-1

multicloud-restore-2

multicloud-restore-3

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kumarashit** [comment]
Rather than "Do you want to archive this object?" Simply say "Archive"

**Comment by anvithks** [comment]
@kumarashit since this is more of a nit you can create a suggestion issue and merge the PR if there aren't any code changes. We can modify that in the final release.

**Comment by kumarashit** [comment]
> @kumarashit since this is more of a nit you can create a suggestion issue and merge the PR if there aren't any code changes. We can modify that in the final release.

Please take care in next PR.

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
