### PR TITLE
Added a progress bar and notification for copy-paste operation.

### LINKED ISSUE #543: [Multicloud UI] can we show the progress of copy/paste operation when user has pasted an object?
**Issue/Feature Description:**
In the multicloud UI when user copies an object from one bucket and pastes it to another, the process takes place and the object appears in the destination bucket but the user is not shown any loader or progress during this process.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
User may not understand if the paste is under progress and navigate away from the screen.

**How to reproduce, in case of a bug:**
1. Login to SODA Dashboard.
2. Go to the source bucket.
3. Select an object, then select copy from the More menu.
4. Go to the destination bucket. select paste from the more menu.
5. The object gets pasted and appears after some time but the screen does not indicate any activity.

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
 /kind enhancement

**What this PR does / why we need it**:
This PR adds a progress bar to indicate the copy-paste operation progress.
It also adds notification to be shown to the user and inform the user that the pasted object will appear in the destination bucket shortly.

The copy-paste operation is async and the API returns success if it receives the request at the backend.
The backend will  initiate the copy but the paste operation (in-cloud and cross cloud) will take some time depending on the size of the file. Earlier the user had no indication of whether the paste operation is successful and if the file will be pasted in the destination.
With this PR the user will know that the operation is progress and the notification will let the user know that the pasted objects will be available shortly.

**Which issue(s) this PR fixes**:

Fixes #543 

**Test Report Added?**:
/kind TESTED

**Test Report**:
copy-paste-1
copy-paste-2
copy-paste-3

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kumarashit** [comment]
Is it possible to put the progress bar inline or somewhere, where it doesn't overlap the other object listing

**Comment by anvithks** [comment]
> Is it possible to put the progress bar inline or somewhere, where it doesn't overlap the other object listing

If you notice the progress bar is more of a loader. There is no specific time that we can show or for that individual copy progress.
The API shows returns success when the call to our backend is successful. In turn our backend makes the appropriate calls to the cloud backend, the progress of which is not available to us.
This loader lasts about 5-10 seconds at most.
You can see the demo below.
I think this is ok for letting the user know that there is an operation in progress and wait for it to complete before performing any other operation.
https://user-images.githubusercontent.com/19162717/111635295-5e276000-881d-11eb-9aee-bee7e289283b.mp4

**Comment by kumarashit** [comment]
Ok. My main concern is that the loader should not overlap any other items (Ux persepective)

**Comment by anvithks** [comment]
> Ok. My main concern is that the loader should not overlap any other items (Ux persepective)

A loader will prevent user from performing any other actions while the copy is still in progress on the page. You can compare the current implementation and check the difference. 


For your reference I have attached a video of the current implementation.

https://user-images.githubusercontent.com/19162717/111770565-950a7e00-88d0-11eb-95a5-6d6227f1825b.mp4

**Review by kumarashit — APPROVED** [review]
LGTM

**Comment by NajmudheenCT** [comment]
> > Ok. My main concern is that the loader should not overlap any other items (Ux persepective)
> 
> A loader will prevent user from performing any other actions while the copy is still in progress on the page. You can compare the current implementation and check the difference.
> 
> For your reference I have attached a video of the current implementation.
> 
>  copy-paste-no-progress.mp4

Some questions
1. Does the copy-paste  operation wait for the actual backend copy to complete, or just our internal DB copy?
2. if it is actual backend copy, is it a good idea to prevent user from doing any other operation till the copy operation completes?

**Comment by anvithks** [comment]
> > > Ok. My main concern is that the loader should not overlap any other items (Ux persepective)
> > 
> > 
> > A loader will prevent user from performing any other actions while the copy is still in progress on the page. You can compare the current implementation and check the difference.
> > For your reference I have attached a video of the current implementation.
> > copy-paste-no-progress.mp4
> 

@NajmudheenCT 

> Some questions
> 
> 1. Does the copy-paste  operation wait for the actual backend copy to complete, or just our internal DB copy?

Just for the internal DB copy and responds success.

> 2. if it is actual backend copy, is it a good idea to prevent user from doing any other operation till the copy operation completes?

Actual copy takes a while and there is no way for the user to know. But even when the copy operation is in progress a loader should be shown on screen. 

This does not hamper any operations and does not cause any UX issues IMO.
If this was a blocking loader until the cloud copy is complete then it would be a problem.

**Comment by NajmudheenCT** [comment]
> > > > Ok. My main concern is that the loader should not overlap any other items (Ux persepective)
> > > 
> > > 
> > > A loader will prevent user from performing any other actions while the copy is still in progress on the page. You can compare the current implementation and check the difference.
> > > For your reference I have attached a video of the current implementation.
> > > copy-paste-no-progress.mp4
> 
> @NajmudheenCT
> 
> > Some questions
> > 
> > 1. Does the copy-paste  operation wait for the actual backend copy to complete, or just our internal DB copy?
> 
> Just for the internal DB copy and responds success.
> 
> > 1. if it is actual backend copy, is it a good idea to prevent user from doing any other operation till the copy operation completes?
> 
> Actual copy takes a while and there is no way for the user to know. But even when the copy operation is in progress a loader should be shown on screen.
> 
> This does not hamper any operations and does not cause any UX issues IMO.
> If this was a blocking loader until the cloud copy is complete then it would be a problem.

Thanks..

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Pull request merged**
