### PR TITLE
Added disk support to delfin UI storage details

### PR DESCRIPTION
**Pull request by anvithks**
## Depends on #490 . Please merge this PR only after #490
**What type of PR is this?**
/kind new feature
> /kind enhancement

**What this PR does / why we need it**:
This PR adds disk support to Delfin UI storage details page.
**Which issue(s) this PR fixes**:
Fixes: This PR completes the issue #463 

**Test Report Added?**:
/kind TESTED

**Test Report**:
disk-1
disk-2
disk-3

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kumarashit** [comment]
What does createdAt and updated at signifies? DB ? This seems little confusing

**Comment by anvithks** [comment]
> What does createdAt and updated at signifies? DB ? This seems little confusing

These are as per the API response.
Let me know if it needs to be changed.

**Comment by anvithks** [comment]
@kumarashit @wisererik 
If the createdAt and updatedAt fields are not relevant and only needed at the DB level we can remove them from the display of Disks, Controllers and Ports.
Something like this:
image

Let me know how to proceed.

**Review by wisererik — COMMENTED** [review]
Hi anvithks, IMO, the created_time, updated_time should not be showed, because they are internal status for when to collect and update data.

**Comment by anvithks** [comment]
> Hi anvithks, IMO, the created_time, updated_time should not be showed, because they are internal status for when to collect and update data.

Alright. I will hide these from the table column. Do you want me to remove them from the details view on expanding?

**Comment by wisererik** [comment]
> > Hi anvithks, IMO, the created_time, updated_time should not be showed, because they are internal status for when to collect and update data.
> 
> Alright. I will hide these from the table column. Do you want me to remove them from the details view on expanding?

yes, it's better to hide it in details

**Comment by anvithks** [comment]
> > > Hi anvithks, IMO, the created_time, updated_time should not be showed, because they are internal status for when to collect and update data.
> > 
> > 
> > Alright. I will hide these from the table column. Do you want me to remove them from the details view on expanding?
> 
> yes, it's better to hide it in details
@wisererik 
So we do not show the createdAt and updatedAt fields at all anywhere in the dashboard for Disks, Controllers and ports?

**Comment by anvithks** [comment]
@kumarashit @wisererik @skdwriting Updated the PR 
Removed the created and updated time.
image

**Comment by kumarashit** [comment]
> > > > Hi anvithks, IMO, the created_time, updated_time should not be showed, because they are internal status for when to collect and update data.
> > > 
> > > 
> > > Alright. I will hide these from the table column. Do you want me to remove them from the details view on expanding?
> > 
> > 
> > yes, it's better to hide it in details
> 
> @wisererik
> So we do not show the createdAt and updatedAt fields at all anywhere in the dashboard for Disks, Controllers and ports?

Yes

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
